### ISSUE TITLE
ppsd "save DB" errors..

### ISSUE THREAD

**Issue by Woondo** [ProjectISP/ISP#13]
First of all, thank you so much for making such a great program.

While I was installing and using this program, I found one problem.

In the PPSD session, for example, if I set the HHZ component and press the "process" button to complete the process, I cannot save.
If you click save DB as shown in the attached picture,
I was able to select only "directories" instead of "file"...
is it originally like that?
![PPSD_save DB](https://github.com/ProjectISP/ISP/assets/108471294/aa272ac1-8408-42ef-95d0-f2e8d50f5b3a)

Or is there another SAVE function? I would appreciate it if you could let me know.

**Comment by rcabdia** [comment]
Thank you so much for testing and enjoy ISP.
So, I guess that you generate the database and then you plot the ppsds.
1) if you set HHZ as filter you just have to point to the root directory to process your daily mseeds because ISP is going to automatically check tall files inside that folder and filter if it is HHZ channel from the header.
2) Once is computed the PPSDs, the DB can be saved in any directory as you hilighted in your comment and the name of the database had to be given by the user in "DB Name" inside process PPSDs widget dialog https://projectisp.github.io/ISP_tutorial.github.io/ppsds/

Please let me know if this info has helped you?

Roberto

**Comment by Woondo** [comment]
Hi Roberto

thank you so much for your kind reply

But now, when I run the ISP program and press the PPSD button, this error message pops up and the window is not activated...
The error message is as below
Traceback (most recent call last):
   File "/home/kdw/ISP/isp/Gui/controllers/window_controller.py", line 108, in ppsds
     self.ppds_frame = PPSDFrame()
   File "/home/kdw/ISP/isp/Gui/Frames/main.py", line 11, in __call__
     obj.__load__()
   File "/home/kdw/ISP/isp/Gui/Frames/main.py", line 22, in __load__
     self.load()
   File "/home/kdw/ISP/isp/Gui/Frames/main.py", line 48, in load
     load_preferences(self)
   File "/home/kdw/ISP/isp/Gui/Utils/pyqt_utils.py", line 58, in load_preferences
     item.load_values()
   File "/home/kdw/ISP/isp/Gui/Utils/pyqt_utils.py", line 89, in load_values
     load_preferences(self)
   File "/home/kdw/ISP/isp/Gui/Utils/pyqt_utils.py", line 56, in load_preferences
     for key, item in pyqt_object.__dict__.items():
RuntimeError: dictionary changed size during iteration


I had this problem just a while ago, so after about 20 minutes, I pressed the ppsd button again, and it worked fine... Again, this problem suddenly occurs...

And it's extra, but https://projectisp.github.io/ISP_tutorial.github.io/ppsds/
Can you tell me when to use continue process in the process PPSD menu?

I'm sorry for asking every time
![1](https://github.com/ProjectISP/ISP/assets/108471294/c1ad7345-8d53-4dcb-8432-f2a0f159efab)

**Comment by rcabdia** [comment]
You are welcome to ask as many times as you want and share ISP with everyone to help more and more people.


Yes, I remember this small bug. So the issue seems to be related with the configuration saved in your system in previous ISP sessions.

For example for me is in /Users/admin/Library/Preferences/com.isp.user_pref.plist.

(isp) admin@iMac-de-Admin ISP % python start_isp.py 
Database started at the url: sqlite:////Users/admin/Documents/iMacROA/ISP/isp/Gui/isp_test.db
qt.qpa.fonts: Populating font family aliases took 339 ms. Replace uses of missing font family "DejaVu Sans" with one that exists to avoid this cost. 
libpng warning: iCCP: known incorrect sRGB profile
Missing colon in file '/Users/admin/Documents/iMacROA/ISP/isp/Gui/StyleLib/isp.mplstyle', line 12 ('figure.constrained_layout.use = True')
2023-07-06 17:55:22,681 - logger - INFO - ISP GUI Started
2023-07-06 17:55:22,682 - logger - INFO - User preferences is at: **/Users/admin/Library/Preferences/com.isp.user_pref.plist**

When you start isp, in the command line is stated where is placed this file in your system

So just delete the file com.isp.user_pref.plist in your system and then restart ISP, ISP will automatically generate a new fresh file. Might be you have been able to restart the toolboox because you entered in another different module and that reset the preferences.

I will ask Andress about the functionality of "continue" inside PPSD toolbox. :-)

**Comment by Woondo** [comment]
> Robert

If you use the variation function of PPSD,
Is it possible to plot multiple channels simultaneously?

I saved the calculations with ppsd as a DB file and loaded them using the load DB function.
Then, when I clicked several imported files at the same time and pressed the plot button, an error message occurred as shown in the attached picture...


The error code is below...
Traceback (most recent call last):
   File "/home/kdw/ISP/isp/Gui/Frames/ppsds_frame.py", line 159, in plot_ppsds
     ppsd = self.ppsd_db['nets'][ntwk][stnm][chnm][1]
KeyError: 'KG'

May I know how can I fix this problem?

Thank you for making such a great program.

![multy plot error](https://github.com/ProjectISP/ISP/assets/108471294/e2d89f49-5fc1-40f6-b7cb-6f26c0e02126)

**Comment by rcabdia** [comment]
Ok, only way to understand this error is trying to replicate it by myself.
Do you mind send me some mseed files and the corresponding metadata to replicate it an debug it. you can email me directly or post a link to with the link

It is super helpful that users like you give me this feedback!!! :-)

**Comment by Woondo** [comment]
(ISP PPSD DB file)JSB_HHZ
<https://drive.google.com/file/d/1p_CLdbho1oWicNBjeGP23MWDQUJnVz4F/view?usp=drive_web>
 (ISP PPSD DB file)JSTB_HHZ
<https://drive.google.com/file/d/1rqcvMSIyQ0oMfBQwwu9iIR-4scnZRvNw/view?usp=drive_web>
 KG.JSB.HHZ.2022.019.00.00.zip
<https://drive.google.com/file/d/1uM6XJykH3ieSOCblUUCxZibInZhwMaNN/view?usp=drive_web>
 KS.JSTB.HHZ.2022.001_030.00.00.zip
<https://drive.google.com/file/d/15-axkn0ds0HMp_65RtKV5Ac_hOhJt9EW/view?usp=drive_web>
 RESP.KG.JSB..HHZ
<https://drive.google.com/file/d/1YrDddYByy3Cxt2pkUf3Cq90WoGB4n72S/view?usp=drive_web>
 RESP.KS.JSTB..HHZ
<https://drive.google.com/file/d/1i9JhOCBU9MR5MAq1nU_olUHQ99gUCVOX/view?usp=drive_web>
hi robert


When posting a question on github, the network codes are KS and KG as shown
in the attached picture.
We will send you two types of miniseed file bundles.

Miniseed files are originally made using one year of data
I created an ISP PPSD DB file.
However, since the volume is too large, only a portion of the data (about
30 days) is compressed and sent.

And I also attached each response (metadata) file.

And just in case you didn't know, I also attached the ISP PPSD DB file.

And the reason why my reply is late lately is because I'm using various
features of the ISP and because of various other tasks... I'm sorry.

I sincerely wish you always full of luck

thank you

2023년 7월 29일 (토) 오전 1:59, Roberto Cabieces Díaz ***@***.***>님이
작성:
